-- luacheck for an ALE (AzerothCore Lua Engine) script.
-- ALE loads scripts under LuaJIT, 5.1, 5.2, 5.3 or 5.4 depending on the
-- build, so the accepted language is the intersection: "max" is every
-- standard at once, and the compile step in CI checks 5.1 and 5.4 for real.
std = "max"

-- Every global ALE registers (mod-ale src/LuaEngine/methods/GlobalMethods.h).
read_globals = {
    "AddTaxiPath",
    "AddVendorItem",
    "AuthDBExecute",
    "AuthDBQuery",
    "AuthDBQueryAsync",
    "Ban",
    "CharDBExecute",
    "CharDBQuery",
    "CharDBQueryAsync",
    "ClearAllCreatureEvents",
    "ClearBattleGroundEvents",
    "ClearCreatureEvents",
    "ClearCreatureGossipEvents",
    "ClearGameObjectEvents",
    "ClearGameObjectGossipEvents",
    "ClearGroupEvents",
    "ClearGuildEvents",
    "ClearInstanceEvents",
    "ClearItemEvents",
    "ClearItemGossipEvents",
    "ClearMapEvents",
    "ClearPacketEvents",
    "ClearPlayerEvents",
    "ClearPlayerGossipEvents",
    "ClearServerEvents",
    "ClearSpellEvents",
    "ClearTicketEvents",
    "ClearUniqueCreatureEvents",
    "CreateLongLong",
    "CreateLuaEvent",
    "CreatePacket",
    "CreateULongLong",
    "GetActiveGameEvents",
    "GetAreaName",
    "GetConfigValue",
    "GetCoreExpansion",
    "GetCoreName",
    "GetCoreVersion",
    "GetCurrTime",
    "GetGUIDEntry",
    "GetGUIDLow",
    "GetGUIDType",
    "GetGameTime",
    "GetGossipMenuOptionLocale",
    "GetGuildByLeaderGUID",
    "GetGuildByName",
    "GetItemGUID",
    "GetItemLink",
    "GetItemTemplate",
    "GetLuaEngine",
    "GetMapById",
    "GetMapEntrance",
    "GetObjectGUID",
    "GetOwnerHalaa",
    "GetPackedGUIDSize",
    "GetPlayerByGUID",
    "GetPlayerByName",
    "GetPlayerCount",
    "GetPlayerGUID",
    "GetPlayersInWorld",
    "GetQuest",
    "GetRealmID",
    "GetSpellInfo",
    "GetStateInstanceId",
    "GetStateMap",
    "GetStateMapId",
    "GetTimeDiff",
    "GetUnitGUID",
    "HttpRequest",
    "IsBagPos",
    "IsBankPos",
    "IsCompatibilityMode",
    "IsEquipmentPos",
    "IsGameEventActive",
    "IsInventoryPos",
    "Kick",
    "LookupEntry",
    "PerformIngameSpawn",
    "PrintDebug",
    "PrintError",
    "PrintInfo",
    "RegisterAllCreatureEvent",
    "RegisterBGEvent",
    "RegisterCreatureEvent",
    "RegisterCreatureGossipEvent",
    "RegisterGameObjectEvent",
    "RegisterGameObjectGossipEvent",
    "RegisterGroupEvent",
    "RegisterGuildEvent",
    "RegisterInstanceEvent",
    "RegisterItemEvent",
    "RegisterItemGossipEvent",
    "RegisterMapEvent",
    "RegisterPacketEvent",
    "RegisterPlayerEvent",
    "RegisterPlayerGossipEvent",
    "RegisterServerEvent",
    "RegisterSpellEvent",
    "RegisterTicketEvent",
    "RegisterUniqueCreatureEvent",
    "RemoveEventById",
    "RemoveEvents",
    "RunCommand",
    "SendMail",
    "SendWorldMessage",
    "SetOwnerHalaa",
    "StartGameEvent",
    "StopGameEvent",
    "VendorRemoveAllItems",
    "VendorRemoveItem",
    "WorldDBExecute",
    "WorldDBQuery",
    "WorldDBQueryAsync",
}

-- Event callbacks take (event, player, ...) and rarely use all of them.
unused_args = false

max_line_length = false
